### ISSUE TITLE
Spherogram/planarity_src/planarity.c Not Found

### ISSUE THREAD

**Issue by zitterbewegung** [3-manifolds/Spherogram#2]
Hi, I get this error from installing this from source as a library there is an issue with the setup.py. I was able to copy planarity.c to the parent directory to fix.

running install
running bdist_egg
running egg_info
creating spherogram.egg-info
writing spherogram.egg-info/PKG-INFO
writing dependency_links to spherogram.egg-info/dependency_links.txt
writing requirements to spherogram.egg-info/requires.txt
writing top-level names to spherogram.egg-info/top_level.txt
writing manifest file 'spherogram.egg-info/SOURCES.txt'
reading manifest file 'spherogram.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'planarity_src/planarity.c'
warning: no files found matching 'planarmap_src/planarmap.c'
writing manifest file 'spherogram.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.15-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.15-x86_64-3.7
creating build/lib.macosx-10.15-x86_64-3.7/spherogram
copying spherogram_src/presentations.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram
copying spherogram_src/test_helper.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram
copying spherogram_src/version.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram
copying spherogram_src/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram
copying spherogram_src/sage_helper.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram
copying spherogram_src/test.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram
copying spherogram_src/graphs.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram
creating build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/simplify.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/links_base.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/torus.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/links.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/twist.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/extra_tests.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/planar_isotopy.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/seifert.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/orthogonal.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/random_links.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/alexander.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/morse.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/tangles.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/ordered_set.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/draw.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/invariants.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
copying spherogram_src/links/jones.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
creating build/lib.macosx-10.15-x86_64-3.7/spherogram/links/test
copying spherogram_src/links/test/test_montesinos.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links/test
copying spherogram_src/links/test/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links/test
copying spherogram_src/links/test/old_testing_code.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links/test
creating build/lib.macosx-10.15-x86_64-3.7/spherogram/codecs
copying spherogram_src/codecs/Base64LikeDT.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/codecs
copying spherogram_src/codecs/DT.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/codecs
copying spherogram_src/codecs/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/codecs
creating build/lib.macosx-10.15-x86_64-3.7/spherogram/dev
copying dev/dt_tests.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev
copying dev/dt_issue.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev
copying dev/sage_graph.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev
copying dev/sage_link_compare.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev
copying dev/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev
copying dev/signature.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev
copying dev/tangle_patch.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev
copying dev/DTcodes.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev
creating build/lib.macosx-10.15-x86_64-3.7/spherogram/dev/dev_jennet
copying dev/dev_jennet/AlexanderKauffman.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev/dev_jennet
copying dev/dev_jennet/bridge_finding.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev/dev_jennet
copying dev/dev_jennet/__init__.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev/dev_jennet
copying dev/dev_jennet/spanning_trees.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev/dev_jennet
copying dev/dev_jennet/test_links.py -> build/lib.macosx-10.15-x86_64-3.7/spherogram/dev/dev_jennet
copying spherogram_src/links/doc.pdf -> build/lib.macosx-10.15-x86_64-3.7/spherogram/links
running build_ext
building 'spherogram.planarity' extension
creating build/temp.macosx-10.15-x86_64-3.7
creating build/temp.macosx-10.15-x86_64-3.7/planarity_src
creating build/temp.macosx-10.15-x86_64-3.7/planarity_src/c
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -Iplanarity_src/c/ -I/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c planarity_src/planarity.c -o build/temp.macosx-10.15-x86_64-3.7/planarity_src/planarity.o
clang: error: no such file or directory: 'planarity_src/planarity.c'
clang: error: no input files
error: command 'clang' failed with exit status 1
(

**Comment by NathanDunfield** [comment]
Closed by https://github.com/3-manifolds/Spherogram/commit/29eea44b09ce0def9320f317ed82d0426cc5e8d6 .
